
package com.conway.pangpang.integration.ws.traintime;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * 高效/快捷/实时,为您打造全方位云数据服务。  电话：029-68859950  了解更多访问:<a href='http://www.36wu.com' target='_blank'>http://www.36wu.com</a>
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TrainService", targetNamespace = "Yangzhili", wsdlLocation = "http://webservice.36wu.com/TrainService.asmx?wsdl")
public class TrainService
    extends Service
{

    private final static URL TRAINSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.conway.pangpang.integration.ws.traintime.TrainService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.conway.pangpang.integration.ws.traintime.TrainService.class.getResource(".");
            url = new URL(baseUrl, "http://webservice.36wu.com/TrainService.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://webservice.36wu.com/TrainService.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TRAINSERVICE_WSDL_LOCATION = url;
    }

    public TrainService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrainService() {
        super(TRAINSERVICE_WSDL_LOCATION, new QName("Yangzhili", "TrainService"));
    }

    /**
     * 
     * @return
     *     returns TrainServiceSoap
     */
    @WebEndpoint(name = "TrainServiceSoap")
    public TrainServiceSoap getTrainServiceSoap() {
        return super.getPort(new QName("Yangzhili", "TrainServiceSoap"), TrainServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrainServiceSoap
     */
    @WebEndpoint(name = "TrainServiceSoap")
    public TrainServiceSoap getTrainServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("Yangzhili", "TrainServiceSoap"), TrainServiceSoap.class, features);
    }

}
