
package com.conway.pangpang.integration.ws.traintime;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TrainServiceSoap", targetNamespace = "Yangzhili")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrainServiceSoap {


    /**
     * <h3>车次详情查询</h3>输入参数:车次，依据该车次代码返回实体集。trainNumber：车次，Traintype：类型，StationNo：站次，Station：站名，Day：日期，ArriveTime：到达时间，DepartureTime：开车时间，Mileage：里程，查询过程失败或异常TrainNumber为False。
     * 
     * @param userId
     * @param trainNumber
     * @return
     *     returns com.conway.pangpang.integration.ws.ArrayOfTrainDetailInfo
     */
    @WebMethod(operationName = "GetTrainDetailInfoByTrainNumber", action = "Yangzhili/GetTrainDetailInfoByTrainNumber")
    @WebResult(name = "GetTrainDetailInfoByTrainNumberResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "GetTrainDetailInfoByTrainNumber", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTrainDetailInfoByTrainNumber")
    @ResponseWrapper(localName = "GetTrainDetailInfoByTrainNumberResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTrainDetailInfoByTrainNumberResponse")
    public ArrayOfTrainDetailInfo getTrainDetailInfoByTrainNumber(
        @WebParam(name = "trainNumber", targetNamespace = "Yangzhili")
        String trainNumber,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>车次详情查询（JSON）</h3>输入参数:车次，依据该车次代码返回JSON数据。trainNumber：车次，Traintype：类型，StationNo：站次，Station：站名，Day：日期，ArriveTime：到达时间，DepartureTime：开车时间，Mileage：里程，查询过程失败或异常TrainNumber为False。
     * 
     * @param userId
     * @param trainNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetJsonDetailInfoByTrainNumber", action = "Yangzhili/GetJsonDetailInfoByTrainNumber")
    @WebResult(name = "GetJsonDetailInfoByTrainNumberResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "GetJsonDetailInfoByTrainNumber", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetJsonDetailInfoByTrainNumber")
    @ResponseWrapper(localName = "GetJsonDetailInfoByTrainNumberResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetJsonDetailInfoByTrainNumberResponse")
    public String getJsonDetailInfoByTrainNumber(
        @WebParam(name = "trainNumber", targetNamespace = "Yangzhili")
        String trainNumber,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>站到站查询</h3>输入参数:发车站和目的站，依据输入的站名返回实体集。TrainNumber：车次，Traintype：类型，FirstStation：始发站，TerminalStation：终点站，StartStation：出发站，StartTime：发车时间，ArriveStation：目的站，ArriveTime：到达目的站的时间，UseTime：用时，Mileage：出发站到达目的站的里程，查询过程失败或异常TrainNumber为False。
     * 
     * @param startStation
     * @param userId
     * @param arriveStation
     * @return
     *     returns com.conway.pangpang.integration.ws.ArrayOfTrainInfo
     */
    @WebMethod(operationName = "GetTrainStationToStation", action = "Yangzhili/GetTrainStationToStation")
    @WebResult(name = "GetTrainStationToStationResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "GetTrainStationToStation", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTrainStationToStation")
    @ResponseWrapper(localName = "GetTrainStationToStationResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTrainStationToStationResponse")
    public ArrayOfTrainInfo getTrainStationToStation(
        @WebParam(name = "startStation", targetNamespace = "Yangzhili")
        String startStation,
        @WebParam(name = "arriveStation", targetNamespace = "Yangzhili")
        String arriveStation,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>站到站查询（JSON）</h3>输入参数:发车站和目的站，依据输入的站名返回JSON数据。TrainNumber：车次，Traintype：类型，FirstStation：始发站，TerminalStation：终点站，StartStation：出发站，StartTime：发车时间，ArriveStation：目的站，ArriveTime：到达目的站的时间，UseTime：用时，Mileage：出发站到达目的站的里程，查询过程失败或异常TrainNumber为False。
     * 
     * @param startStation
     * @param userId
     * @param arriveStation
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetJsonTrainStationToStation", action = "Yangzhili/GetJsonTrainStationToStation")
    @WebResult(name = "GetJsonTrainStationToStationResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "GetJsonTrainStationToStation", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetJsonTrainStationToStation")
    @ResponseWrapper(localName = "GetJsonTrainStationToStationResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetJsonTrainStationToStationResponse")
    public String getJsonTrainStationToStation(
        @WebParam(name = "startStation", targetNamespace = "Yangzhili")
        String startStation,
        @WebParam(name = "arriveStation", targetNamespace = "Yangzhili")
        String arriveStation,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

}
