
package com.conway.pangpang.integration.ws.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WeatherServiceSoap", targetNamespace = "Yangzhili")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherServiceSoap {


    /**
     * <h3>经纬度查询未来六天天气</h3>输入参数:lng(经度值)，lat(纬度值)。City：城市，Cityid：城市Id（查询结果异常时“False”）,Temp1~Temp6：六天的气温，Weather1~Weather6：六天的天气，Wind1~Wind6：六天的风向，Fl1~Fl6：六天的风力，Img1~Img12：六天天气图片
     * 
     * @param userId
     * @param lng
     * @param lat
     * @return
     *     returns com.conway.pangpang.integration.ws.MoreWeather
     */
    @WebMethod(action = "Yangzhili/getMoreWeatherByLocation")
    @WebResult(name = "getMoreWeatherByLocationResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getMoreWeatherByLocation", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetMoreWeatherByLocation")
    @ResponseWrapper(localName = "getMoreWeatherByLocationResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetMoreWeatherByLocationResponse")
    public MoreWeather getMoreWeatherByLocation(
        @WebParam(name = "lng", targetNamespace = "Yangzhili")
        String lng,
        @WebParam(name = "lat", targetNamespace = "Yangzhili")
        String lat,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>查询未来六天天气</h3>输入参数:CityId，依据CityId查询未来六天天气数据信息。City：城市，Cityid：城市Id（查询结果异常时“False”）,Temp1~Temp6：六天的气温，Weather1~Weather6：六天的天气，Wind1~Wind6：六天的风向，Fl1~Fl6：六天的风力，Img1~Img12：六天天气图片
     * 
     * @param cityId
     * @param userId
     * @return
     *     returns com.conway.pangpang.integration.ws.MoreWeather
     */
    @WebMethod(action = "Yangzhili/getMoreWeatherByCityId")
    @WebResult(name = "getMoreWeatherByCityIdResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getMoreWeatherByCityId", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetMoreWeatherByCityId")
    @ResponseWrapper(localName = "getMoreWeatherByCityIdResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetMoreWeatherByCityIdResponse")
    public MoreWeather getMoreWeatherByCityId(
        @WebParam(name = "CityId", targetNamespace = "Yangzhili")
        String cityId,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>查询当天天气</h3>输入参数:CityId，依据CityId返回当天天气数据信息。City：城市，Cityid：城市Id（查询结果异常时“False”）,Temp1：最高温度，Temp2：最低温度，Weather：天气，Img1~Img2：天气图标，Ptime：发布时间
     * 
     * @param cityId
     * @param userId
     * @return
     *     returns com.conway.pangpang.integration.ws.TodayWeather
     */
    @WebMethod(action = "Yangzhili/getTodayWeatherByCityId")
    @WebResult(name = "getTodayWeatherByCityIdResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getTodayWeatherByCityId", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTodayWeatherByCityId")
    @ResponseWrapper(localName = "getTodayWeatherByCityIdResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTodayWeatherByCityIdResponse")
    public TodayWeather getTodayWeatherByCityId(
        @WebParam(name = "CityId", targetNamespace = "Yangzhili")
        String cityId,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>返回所有CityId</h3>输入参数:无，CityName：城市（查询结果异常时“False”），Cityid：城市Id,Temp1：最高温度，Temp2：最低温度，Weather：天气，Img1~Img2：天气图标，Ptime：发布时间
     * 
     * @param userId
     * @return
     *     returns com.conway.pangpang.integration.ws.ArrayOfWeatherCity
     */
    @WebMethod(action = "Yangzhili/getWeatherCity")
    @WebResult(name = "getWeatherCityResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getWeatherCity", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetWeatherCity")
    @ResponseWrapper(localName = "getWeatherCityResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetWeatherCityResponse")
    public ArrayOfWeatherCity getWeatherCity(
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>经纬度查询当天天气</h3>输入参数:输入参数:lng(经度值)，lat(纬度值)。City：城市，Cityid：城市Id（查询结果异常时“False”）,Temp1：最高温度，Temp2：最低温度，Weather：天气，Img1~Img2：天气图标，Ptime：发布时间
     * 
     * @param userId
     * @param lng
     * @param lat
     * @return
     *     returns com.conway.pangpang.integration.ws.TodayWeather
     */
    @WebMethod(action = "Yangzhili/getTodayWeatherByCityLocation")
    @WebResult(name = "getTodayWeatherByCityLocationResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getTodayWeatherByCityLocation", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTodayWeatherByCityLocation")
    @ResponseWrapper(localName = "getTodayWeatherByCityLocationResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTodayWeatherByCityLocationResponse")
    public TodayWeather getTodayWeatherByCityLocation(
        @WebParam(name = "lng", targetNamespace = "Yangzhili")
        String lng,
        @WebParam(name = "lat", targetNamespace = "Yangzhili")
        String lat,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>查询当天天气</h3>输入参数:城市或县区名，依据参数返回当天天气数据信息。City：城市，Cityid：城市Id（查询结果异常时“False”）,Temp1：最高温度，Temp2：最低温度，Weather：天气，Img1~Img2：天气图标，Ptime：发布时间
     * 
     * @param userId
     * @param cityName
     * @return
     *     returns com.conway.pangpang.integration.ws.TodayWeather
     */
    @WebMethod(action = "Yangzhili/getTodayWeatherByCityName")
    @WebResult(name = "getTodayWeatherByCityNameResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getTodayWeatherByCityName", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTodayWeatherByCityName")
    @ResponseWrapper(localName = "getTodayWeatherByCityNameResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetTodayWeatherByCityNameResponse")
    public TodayWeather getTodayWeatherByCityName(
        @WebParam(name = "CityName", targetNamespace = "Yangzhili")
        String cityName,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>查询未来六天天气</h3>输入参数:城市或县区名，依据参数查询未来六天天气数据信息。City：城市，Cityid：城市Id（查询结果异常时“False”）,Temp1~Temp6：六天的气温，Weather1~Weather6：六天的天气，Wind1~Wind6：六天的风向，Fl1~Fl6：六天的风力，Img1~Img12：六天天气图片
     * 
     * @param userId
     * @param cityName
     * @return
     *     returns com.conway.pangpang.integration.ws.MoreWeather
     */
    @WebMethod(action = "Yangzhili/getMoreWeatherByCityName")
    @WebResult(name = "getMoreWeatherByCityNameResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getMoreWeatherByCityName", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetMoreWeatherByCityName")
    @ResponseWrapper(localName = "getMoreWeatherByCityNameResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetMoreWeatherByCityNameResponse")
    public MoreWeather getMoreWeatherByCityName(
        @WebParam(name = "CityName", targetNamespace = "Yangzhili")
        String cityName,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>根据IP自动获得当地未来六天天气</h3>输入参数:ip，City：城市，Cityid：城市Id（查询结果异常时“False”）,Temp1~Temp6：六天的气温，Weather1~Weather6：六天的天气，Wind1~Wind6：六天的风向，Fl1~Fl6：六天的风力，Img1~Img12：六天天气图片
     * 
     * @param userId
     * @param ip
     * @return
     *     returns com.conway.pangpang.integration.ws.MoreWeather
     */
    @WebMethod(action = "Yangzhili/getAutomaticMoreWeather")
    @WebResult(name = "getAutomaticMoreWeatherResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getAutomaticMoreWeather", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetAutomaticMoreWeather")
    @ResponseWrapper(localName = "getAutomaticMoreWeatherResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetAutomaticMoreWeatherResponse")
    public MoreWeather getAutomaticMoreWeather(
        @WebParam(name = "ip", targetNamespace = "Yangzhili")
        String ip,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>根据IP自动获得当地当天天气</h3>输入参数:ip，City：城市，Cityid：城市Id（查询结果异常时“False”）,Temp1：最高温度，Temp2：最低温度，Weather：天气，Img1~Img2：天气图标，Ptime：发布时间
     * 
     * @param userId
     * @param ip
     * @return
     *     returns com.conway.pangpang.integration.ws.TodayWeather
     */
    @WebMethod(action = "Yangzhili/getAutomaticTodayWeather")
    @WebResult(name = "getAutomaticTodayWeatherResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getAutomaticTodayWeather", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetAutomaticTodayWeather")
    @ResponseWrapper(localName = "getAutomaticTodayWeatherResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetAutomaticTodayWeatherResponse")
    public TodayWeather getAutomaticTodayWeather(
        @WebParam(name = "ip", targetNamespace = "Yangzhili")
        String ip,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>根据CityId查询实时天气</h3>输入参数:CityId，依据CityId返回实时天气数据信息。City：所在地区，Cityid：城市Id（查询结果异常时“False”）,Temp：实时温度,Temp1：最高温度，Temp2：最低温度，Weather：天气，WindDirection：风向，WindForce：风力，Humidity：湿度，Img1~Img2：天气图标
     * 
     * @param cityId
     * @param userId
     * @return
     *     returns com.conway.pangpang.integration.ws.RealTimeWeather
     */
    @WebMethod(action = "Yangzhili/getRealTimeWeatherByCityId")
    @WebResult(name = "getRealTimeWeatherByCityIdResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getRealTimeWeatherByCityId", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetRealTimeWeatherByCityId")
    @ResponseWrapper(localName = "getRealTimeWeatherByCityIdResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetRealTimeWeatherByCityIdResponse")
    public RealTimeWeather getRealTimeWeatherByCityId(
        @WebParam(name = "CityId", targetNamespace = "Yangzhili")
        String cityId,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>根据市区县查询实时天气</h3>输入参数:CityName，依据CityId返回实时天气数据信息。City：所在地区，Cityid：城市Id（查询结果异常时“False”）,Temp：实时温度,Temp1：最高温度，Temp2：最低温度，Weather：天气，WindDirection：风向，WindForce：风力，Humidity：湿度，Img1~Img2：天气图标
     * 
     * @param userId
     * @param cityName
     * @return
     *     returns com.conway.pangpang.integration.ws.RealTimeWeather
     */
    @WebMethod(action = "Yangzhili/getRealTimeWeatherByCityName")
    @WebResult(name = "getRealTimeWeatherByCityNameResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getRealTimeWeatherByCityName", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetRealTimeWeatherByCityName")
    @ResponseWrapper(localName = "getRealTimeWeatherByCityNameResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetRealTimeWeatherByCityNameResponse")
    public RealTimeWeather getRealTimeWeatherByCityName(
        @WebParam(name = "CityName", targetNamespace = "Yangzhili")
        String cityName,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>根据IP查询实时天气</h3>输入参数:CityName，依据CityId返回实时天气数据信息。City：所在地区，Cityid：城市Id（查询结果异常时“False”）,Temp：实时温度,Temp1：最高温度，Temp2：最低温度，Weather：天气，WindDirection：风向，WindForce：风力，Humidity：湿度，Img1~Img2：天气图标
     * 
     * @param userId
     * @param ip
     * @return
     *     returns com.conway.pangpang.integration.ws.RealTimeWeather
     */
    @WebMethod(action = "Yangzhili/getRealTimeWeatherByIp")
    @WebResult(name = "getRealTimeWeatherByIpResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getRealTimeWeatherByIp", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetRealTimeWeatherByIp")
    @ResponseWrapper(localName = "getRealTimeWeatherByIpResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetRealTimeWeatherByIpResponse")
    public RealTimeWeather getRealTimeWeatherByIp(
        @WebParam(name = "ip", targetNamespace = "Yangzhili")
        String ip,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>根据CityID查询生活指数</h3>输入参数:CityId，依据CityId返回生活指数数据信息。Cityid：城市Id（查询结果异常时“False”）,Name：指数,Hint：适宜度，Temp2：最低温度，Des：详细信息
     * 
     * @param cityId
     * @param userId
     * @return
     *     returns com.conway.pangpang.integration.ws.WeatherIndex
     */
    @WebMethod(action = "Yangzhili/getExponentByCityId")
    @WebResult(name = "getExponentByCityIdResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getExponentByCityId", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetExponentByCityId")
    @ResponseWrapper(localName = "getExponentByCityIdResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetExponentByCityIdResponse")
    public WeatherIndex getExponentByCityId(
        @WebParam(name = "CityId", targetNamespace = "Yangzhili")
        String cityId,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

    /**
     * <h3>根据城市/区/县查询生活指数</h3>输入参数:CityName，依据城市/区/县返回生活指数数据信息。Cityid：城市Id（查询结果异常时“False”）,Name：指数,Hint：适宜度，Temp2：最低温度，Des：详细信息
     * 
     * @param userId
     * @param cityName
     * @return
     *     returns com.conway.pangpang.integration.ws.WeatherIndex
     */
    @WebMethod(action = "Yangzhili/getExponentByCityName")
    @WebResult(name = "getExponentByCityNameResult", targetNamespace = "Yangzhili")
    @RequestWrapper(localName = "getExponentByCityName", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetExponentByCityName")
    @ResponseWrapper(localName = "getExponentByCityNameResponse", targetNamespace = "Yangzhili", className = "com.conway.pangpang.integration.ws.GetExponentByCityNameResponse")
    public WeatherIndex getExponentByCityName(
        @WebParam(name = "CityName", targetNamespace = "Yangzhili")
        String cityName,
        @WebParam(name = "UserId", targetNamespace = "Yangzhili")
        String userId);

}
